Update

diff --git a/bin/setup-wacom b/bin/setup-wacom
--- a/bin/setup-wacom
+++ b/bin/setup-wacom
@@ -1,40 +1,40 @@
 #!/usr/bin/bash
 
-# Left: 1600x1200, Right: 1280x800
-#   left:                                right:
-# [ 1600/(1600+1280)  0          0 ]   [ 1280/(1600+1280)  0         1600/(1600+1280)]
-# [ 0                 1200/1200  0 ]   [ 0                 800/1200  0               ]
-# [ 0                 0          1 ]   [ 0                 0         1               ]
-#
-# see https://github.com/linuxwacom/xf86-input-wacom/wiki/Dual-and-Multi-Monitor-Set-Up
+set -euo pipefail
 
-LEFT=
-RIGHT=1
-TARGET_DEVIVE=10
+DEVICE_NAME="Wacom Intuos S 2 Pen"
+DEFAULT_OUTPUT="DP-1"
 
-LEFT_W=1920.0
-LEFT_H=1080.0
-RIGHT_W=2560.0
-RIGHT_H=1440.0
+output="${1:-$DEFAULT_OUTPUT}"
 
-if (( $(echo "$LEFT_H > $RIGHT_H" | bc -l) )); then
-  LARGER_HEIGHT=$LEFT_H
-else
-  LARGER_HEIGHT=$RIGHT_H
+base_path="/org/kde/KWin/InputDevice"
+
+# List event nodes via DBus introspection
+nodes=$(qdbus6 org.kde.KWin "$base_path" org.freedesktop.DBus.Introspectable.Introspect 2>/dev/null \
+    | grep -oP 'node name="\Kevent[^"]+')
+
+event_node=""
+for node in $nodes; do
+    name=$(qdbus6 org.kde.KWin "$base_path/$node" \
+        org.freedesktop.DBus.Properties.Get "org.kde.KWin.InputDevice" name 2>/dev/null || true)
+    if [[ "$name" == "$DEVICE_NAME" ]]; then
+        event_node="$node"
+        break
+    fi
+done
+
+if [[ -z "$event_node" ]]; then
+    echo "Error: '$DEVICE_NAME' not found" >&2
+    exit 1
 fi
 
-if [ -n "$LEFT" ]; then
-  echo LEFT
-  a=$(echo "scale=7; $LEFT_W / ($LEFT_W + $RIGHT_W)" | bc)
-  b=0
-  c=$(echo "scale=7; $LEFT_H / $LARGER_HEIGHT" | bc)
-else
-  echo RIGHT
-  a=$(echo "scale=7; $RIGHT_W / ($LEFT_W + $RIGHT_W)" | bc)
-  b=$(echo "scale=7; $LEFT_W / ($LEFT_W + $RIGHT_W)" | bc)
-  c=$(echo "scale=7; $RIGHT_H / $LARGER_HEIGHT" | bc)
-fi
+dbus_path="$base_path/$event_node"
 
-set -x
-xinput set-prop $TARGET_DEVIVE --type=float "Coordinate Transformation Matrix" $a 0 $b 0 $c 0 0 0 1
-# xsetwacom --set 10 MapToOutput "2560x1440+1920+0"
+echo "Device: $DEVICE_NAME ($event_node)"
+echo "Mapping to: $output"
+
+qdbus6 org.kde.KWin "$dbus_path" \
+    org.freedesktop.DBus.Properties.Set \
+    "org.kde.KWin.InputDevice" outputName "$output"
+
+echo "Done"
